name: CI

on:
  push:
    branches: [ master, wip ]
  pull_request:
    branches: [ master, wip ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows:
    strategy:
      matrix:
        os: [windows-11-arm, windows-2022, windows-2025 ]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - name: Show platform
        shell: bash
        run: |
          uname -m
          echo "Runner OS: $RUNNER_OS"
          echo "Runner arch: $RUNNER_ARCH"
      - name: Run prove
        run: prove t\zdrop.c.bat
      - name: winbash w/o prove -static
        run: bash t\zdrop.c.sh -static bin
      - name: save static build
        shell: bash
        run: for f in bin/*;do mv "$f" "static-$f";done
      - name: winbash w/o prove
        run: bash t\zdrop.c.sh bin
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}
          path: bin/

  linux:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Show platform
        run: |
          uname -m
          dpkg --print-architecture || true
          echo "Runner OS: $RUNNER_OS"
          echo "Runner arch: $RUNNER_ARCH"
      - name: Linux static test
        run: bash t/zdrop.c.sh -static bin
      - name: save static build
        shell: bash
        run: for f in bin/*;do mv "$f" "static-$f";done
      - name: Linux test
        run: bash t/zdrop.c.sh bin
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}
          path: bin/
