name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, wip ]
  pull_request:
    branches: [ master, wip ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows:
    strategy:
      matrix:
        os: [windows-11-arm, windows-2022, windows-latest ]
        bits: [64, 32]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6
      - name: Run prove
        run: prove t\zdrop.c.bat
      - name: winbash w/o prove
        run: bash t\zdrop.c.sh -static bin
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.os }}-${{ matrix.bits }}
          path: bin/

  linux:
    strategy:
      matrix:
        os: [ ubuntu-22.04-arm, ubuntu-24.04-arm, ubuntu-latest ]
        bits: [64, 32]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Linux test
        run: bash t/zdrop.c.sh -static bin
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.os }}-${{ matrix.bits }}
          path: bin/
